### ISSUE TITLE
Nested lists pages

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/futurecoder#100]
In the nested loops chapter, we need to teach nested lists. This is essential for #3.

Important concepts to cover:

1. Working with nested elements by index:
    1. Getting, e.g. `x = arr[i][j]`.
    2. Setting, e.g.  `arr[i][j] = x`.
2. Looping over all nested elements, e.g. `for sub in arr: for x in sub: print(x)`.

These could be in the opposite order: it might make sense to teach 2 before 1. I haven't figured out all the details.

<details><summary> It's possible to teach the concept of getting by nested indices without mentioned nested lists, because a list of strings is already a nested sequence. Click to see how that could look. Does this make it easier to understand nested lists when they're introduced? Maybe, maybe not.</summary>

Exercise: given a list of strings, print the first letter of the second string in the list. For example, given:

    __copyable__
    strings = ["abc", "def", "ghi"]

you should print `d`.

Solution:

    string = strings[1]
    print(string[0])

---

You may have solved it like this:

    string = strings[1]
    print(string[0])

There's a shorter way. `strings[1]` is an expression like any other, and subscripting like `[0]` can be used on
any expression, not just variables. So you can skip the intermediate variable and just do it in one line:

    print(strings[1][0])

Take a good look at this syntax. If it looks new and fancy, it's not. It's just the usual syntax for subscripting,
applied twice.
</details>

Looping over a nested list can be introduced with a simple example like:

```python
    matrix = [
        [1, 2],
        [3, 4],
    ]

    for row in matrix:
        for num in row:
            print(num)
        print('---')
```

<details><summary>Here is one idea for exercising with loops. The user must search for a substring in a nested list of strings (maybe each list represents a book, and each string is a page) but there are different things that could be done when the user finds the substring. Solving all these exercises would be a lightweight way to train thinking about indenting and setting variables correctly. Click for details. </summary>

First exercise: print every string that contains the word:

    word = "hello"
    strings = [
        [
            "hello there",
            "how are you",
        ],
        [
            "goodbye world",
            "hello world",
        ]
    ]

    for sublist in strings:
        for string in sublist:
            if word in string:
                print(string)

Output:

    hello there
    hello world

Next: print a boolean for each sublist indicating if the word exists:

    for sublist in strings:
        present = False
        for string in sublist:
            if word in string:
                present = True
        print(present)

Finally: just print one boolean indicating if the word is present at all:

    present = False
    for sublist in strings:
        for string in sublist:
            if word in string:
                present = True
    print(present)

</details>

<details><summary>It might be nice to end with some exercises that involve both nested loops and (not necessarily nested) indexing. For example, we could take the previous exercises that emulate zip and zip_longest and generalise to a list of strings instead of just two.</summary>

Similar to zip_exercise:

    strings = ["abc", "def", "ghi"]

    for i in range(len(strings[0])):
        line = ""
        for string in strings:
            line += string[i]
        print(line)

Output:

    adg
    beh
    cfi

and zip_longest_exercise:

```python
strings = ["abcqwe", "def", "ghiq"]

lengths = []
for string in strings:
    lengths.append(len(string))
length = max(lengths)

for i in range(length):
    line = ""
    for string in strings:
        if i >= len(string):
            line += " "
        else:
            line += string[i]
    print(line)
```

Output:

    adg
    beh
    cfi
    q q
    w
    e

</details>

Still lots to figure out, and the above ideas are just ideas, not set in stone.

**Comment by spamegg1** [comment]
> It's possible to teach the concept of getting by nested indices without  mentioned nested lists, because a list of strings is already a nested  sequence. Click to see how that could look. Does this make it easier to  understand nested lists when they're introduced? Maybe, maybe not.

I think it does! I like it. They can be introduced to **i. Getting, e.g. `x = arr[i][j]`** without the mental overhead of nested lists that way. 

The issue is that they might think **ii. Setting, e.g.  `arr[i][j] = x`** should work the same way. We'd have to remind them that strings are immutable. Or maybe we should show them that directly.

> Looping over a nested list can be introduced with a simple example like:
>
> ```python
> matrix = [
>      [1, 2],
>      [3, 4],
>  ]
> 
> for row in matrix:
> 	for num in row:
> 		print(num)
> 	print('---')
> ```

I think that's fine. I'm concerned with accidentally forcing the idea that nested lists have to be "square matrices", or that each inner list must have the same length as the others, or that each list must contain the same kind of things.

We should probably have an example with lists of different lengths, containing a mix of numbers and words, and *eventually* get a **list index out of range** error to show them the perils of looping nested lists with `range(len(lst))`. It would be interesting if this came up for the first time inside an exercise (too hard?)

Something like this:

```python
people = [
    ["Alice", 20, "student"],
    ["Bob", 32, "pharmacist", "dog"],
    ["Charlie", 25],
    ["Dylan", 18, "student", "guitar"],
    ["Emily", 54]
]
```

Then we ask them to get a list of just the names, just the ages, just the occupations, just the pets/hobbies... We can show the difference between `len(people)` and `len(people[0])`, `len(people[1])` etc.

Too hard? Or confusing?

We can also show that the list methods they previously learned still work the same way with nested lists. Say we want to add an occupation for `"Charlie"`: 

```python
people[2].append("athlete")
```

> Here is one idea for exercising with loops. The user must search for a  substring in a nested list of strings (maybe each list represents a  book, and each string is a page) but there are different things that  could be done when the user finds the substring. Solving all these  exercises would be a lightweight way to train thinking about indenting  and setting variables correctly. Click for details. 

These are great opportunities to visualize. Let's make them use Python Tutor etc. Also should we take this opportunity to teach them how to build up a nested list (with the booleans)?

> It might be nice to end with some exercises that involve both nested  loops and (not necessarily nested) indexing. For example, we could take  the previous exercises that emulate zip and zip_longest and generalise  to a list of strings instead of just two.

I like these, maybe these should come after "list of strings as nested sequence" exercise and before actual nested lists? These are more like nested loops exercises rather than nested lists. Maybe we can make it cuter, like "a secret message is hidden in the first letters, then in the second letters..."

**Comment by alexmojaki** [comment]
These all sound like good ideas, but yes, the index out of range thing is too much for an exercise.

**Comment by spamegg1** [comment]
OK, I'll leave that out. I'll start cooking up a draft soon.

**Comment by spamegg1** [comment]
Draft (probably needs a lot of work)

<details>
    <summary>Click to expand</summary>

## Nested Lists

### Page: Nested lists

#### Step (ExerciseStep)

Exercise: given a list of strings, print the first letter of the second string in the list. For example, given:

```python
__copyable__
strings = ["abc", "def", "ghi"]
```

you should print `d`.

*Hints:*

*How can you access the second string in the list?*

*What list method/function is used to do that?*

*Then how do you access a particular letter in a string?*

*Remember that the indexing of lists and strings are very similar.*

*Solution:*

```python
strings = ["abc", "def", "ghi"]
string = strings[1]
print(string[0])
```

*user solves Exercise, reaches next Step*

#### Step (ExerciseStep)

You may have solved it like this:

```python
strings = ["abc", "def", "ghi"]
string = strings[1]
print(string[0])
```

There's a shorter way. `strings[1]` is an expression like any other, and subscripting like `[0]` can be used on any expression, not just variables. So you can skip the intermediate variable and just do it in one line:

```python
strings = ["abc", "def", "ghi"]
print(strings[1][0])
```

Take a good look at this syntax. If it looks new and fancy, it's not. It's just the usual syntax for subscripting, applied twice.

Using this syntax, modify the program to print the last letter of the last string in a list. Your solution should work for lists of any length and strings of any positive length. For example, for

```python
__copyable__
strings = ["abc", "de", "fghi", "h", "jk"]
```

it should print `k`.

*Hints:*

*This is very similar to the previous exercise.*

*Do you remember how to access the last position of a list?*

*Solution:*

```python
strings = ["abc", "de", "fghi", "h", "jk"]
print(strings[-1][-1])
```

*user solves Exercise, reaches next Step*

#### Step (VerbatimStep with predicted output)

Applying subscripting twice can be even more powerful. We can use it on not only a list of strings, but on *a list of lists* too. For example, what does the following program print?

```python
matrix = [
        [1, 2],
        [3, 4],
    ]
print(matrix[1][0])
```

*Predicted output:*

- `1`
- `2`
- `3`
- `4`
- `Error`

*user types and runs code, chooses correct output, reaches next Step*

#### Step (VerbatimStep with predicted output)

As you can see Python allows us to have *nested lists*: a list where each element is another list (we refer to them as *sublists*). This idea is very powerful and it will allow us to create more complicated and interesting programs.

Let us combine our knowledge of nested for loops with nested lists. Try this program:

```python
__copyable__  # ??????
matrix = [
     [1, 2, 3],
     [4, 5, 6],
 ]

for row in matrix:
	for num in row:
		print(num)
	print('---')
```

*Predicted output:*

- ```
  1
  ---
  2
  ---
  3
  ---
  4
  ---
  5
  ---
  6
  ---
  ```

- ```
  1
  2
  ---
  3
  4
  ---
  5
  6
  ---
  ```

- ```
  1
  2
  3
  ---
  4
  5
  6
  ---
  ```

- ```
  1 2 3
  ---
  4 5 6
  ---
  ```

- `Error`

*user types and runs code, chooses correct output, reaches next Step*

#### Step (VerbatimStep with Python Tutor)

***there should be more explanation here probably***

Run the program again in Python Tutor. Examine what `matrix` looks like, and what `matrix[0]` and `matrix[1]` are. Look at how `row` and `num` variables advance.

*user runs code on pythontutor.com, reaches next Step*

#### Step (VerbatimStep)

Not every element in a nested list has to be a list like in the previous exercises. Python allows us to mix all kinds together (numbers, strings, other lists) in a list. This is a legitimate list in Python:

```python
person = ['Alice', 25, ['dog', 'cat']]
```

For example this could be a person's name, age, and *a list* of the kinds of pets they own.

We can still use the usual list functions and methods. Let us update the second pet from `'cat'` to `'fish'` by using subscripting twice, but for assignment this time:

```python
person = ['Alice', 25, ['dog', 'cat']]
person[2][1] = 'fish'
print(person)
```

*user types and runs code, reaches next Step*

#### Step (ExerciseStep)

Moreover the sublists inside a list do not have to be of the same length either. The following is a legitimate list:

```python
__copyable__
people = [
    ["Alice", 20, "student"],
    ["Bob", 32, "pharmacist", "dog"],
    ["Charlie", 25],
    ["Dylan", 18, "student", "cat", "guitar"]
]
```

In this case `len(people[0])` returns `3`, while `len(people[1])` returns `4`. 

Exercise: you are given the above nested list of `people`, where each sublist follows the order: *name (string), age (number), occupation (string), pet type (string), hobby (string)*. 

Some kinds of information are missing for some people: for example we don't know if `"Alice"` has a pet, or what `"Charlie"`'s occupation is.

Without modifying `people` manually, but using list functions and methods instead, update `people` to add the following two pieces of information:

- `"Charlie"` has the occupation `"athlete"`,
- `"Alice"` has a pet of type `"fish"`.

*Hints:*

*Which sublist do you need to access to update `"Charlie"`'s info?*

*Which list function/method allows you to add that info to the sublist?*

*Repeat a similar approach for the sublist of `"Alice"`.*

*Solution:*

```python
people[2].append("athlete")
people[0].append("fish")
```

*user solves exercise, runs code, reaches next Step*

#### Step (ExerciseStep)

Now print out only the names and the occupations as follows: if

```python
__copyable__
people = [
    ["Alice", 20, "student", "fish"],
    ["Bob", 32, "pharmacist", "dog"],
    ["Charlie", 25, "athlete"],
    ["Dylan", 18, "student", "cat", "guitar"]
]
```
your program should print

```python
Name: Alice, Occupation: student
Name: Bob, Occupation: pharmacist
Name: Charlie, Occupation: athlete
Name: Dylan, Occupation: student        
```

*Hints:*

*How can you access the name and the occupation in each sublist?*

*You can use an f-string with several variables.*

*Solution:*

```python
for person in people:
    print(f"Name: {person[0]}, Occupation: {person[2]}")
```

*user solves exercise, runs code, reaches final text*

#### Final Text

Good job. On the next page we will exercise more with nested lists.

*user reaches next Page*

### Page

#### Step (ExerciseStep)

Write a program to print every string in a nested list `strings` that contains the given `word`. It should work for any `word` and `strings`. For example, if:

```python
word = "hello"
strings = [
    [
        "hello there",
        "how are you",
    ],
    [
        "goodbye world",
        "hello world",
    ]
]
```

then your program should print

```python
hello there
hello world
```

*Hints:*

*How do you check if a string contains a word?*

*How can you access each string in each sublist of a nested list?*

*Use nested loops.*

*Make sure to check whether **the string** contains the word, not the sublist.*

*Solution:*

```python
for sublist in strings:
    for string in sublist:
        if word in string:
            print(string)
```

*user solves exercise, runs code, reaches next Step*

#### Step (ExerciseStep)

Next, print a boolean for each sublist in `strings` to indicate whether that sublist contains `word`. Your program should work for any `word` and any nested list `strings`. For example, if

```python
__copyable__
word = "goodbye"
strings = [
    [
        "hello there",
        "how are you",
    ],
    [
        "goodbye world",
        "hello world",
    ]
]
```

then your program should print

```python
False
True
```

*Hints:*

*You'll have to use a nested loop once again.*

*For each sublist, define a boolean.*

*What should be the initial value for the boolean?*

*Go through a sublist, update the boolean accordingly.*

*Solution:*

```python
for sublist in strings:
    present = False
    for string in sublist:
        if word in string:
            present = True
    print(present)
```

*user solves exercise, runs code, reaches next Step*

#### Step (ExerciseStep)

Well done. 

Next, print only one boolean to indicate if `word` is present in the entire nested list at all. For example, if

```python
__copyable__
word = "Python"
strings = [
    [
        "hello there",
        "how are you",
    ],
    [
        "goodbye world",
        "hello world",
    ]
]
```

your program should print `False`.

*Hints:*

*This is very similar to the previous exercise.*

*Instead of defining a boolean for each sublist, define only one boolean for the entire list.*

*When and how should you modify the boolean?*

*There is an opportunity to stop a loop early with `break` (although this is not necessary).*

*Solution:*

```python
present = False
for sublist in strings:
    for string in sublist:
        if word in string:
            present = True
print(present)
```

*user solves exercise, runs code, reaches next Step*

#### Step (ExerciseStep)

Well done!

For this exercise you are given a list of strings of **equal length**. Write a program that prints the first letter of each string put together on one line, then the second letter of each string on the next line, and so on. For example, if

```python
strings = ["abc", "def", "ghi"]
```

then your program should print

```python
adg
beh
cfi
```

Your program should work for any such list. In particular, if you use the following list, you'll discover a hidden message from the Zen of Python!

```python
__copyable__
strings = [
    "  b n", "f ete", "liths", "astat", "t ene", "  r d"
]
```

*Hints:*

*You'll need to go through the first letters, then the second letters, and so on.*

*You'll have to use a loop, but how long should the loop take?*

*Remember that strings in the list have equal lengths.*

*For each position (first, second etc.) define a new string.*

*What should that string be initially?*

*For each position (first, second etc.) you'll have to go through each string in the list.*

*You'll need another loop inside the one you have.*

*Solution:*

```python
for i in range(len(strings[0])):
    line = ""
    for string in strings:
        line += string[i]
    print(line)
```

*user solves exercise, runs code, reaches next Step*

#### Step (ExerciseStep)

Excellent! If you'd like, you can just continue to the [next page](/course/?page=DefiningFunctions) now. Or you can do a bonus challenge!

Now let's generalize the previous exercise to strings of unequal length. Once again you are given a list of strings. Like before, write a program that prints the first letter of each string together on one line, then the second letters together on the next line, and so on. But this time, if a string does not have enough letters, it should print a space.

For example, if

```python
strings = ["abcqwe", "def", "ghiq"]
```

your program should print

```python
adg
beh
cfi
q q
w
e
```

*Hints:*

*Since the strings can have different lengths, this is a bit tricky.*

*For how long should your outer loop go this time?*

*Before you start handling the strings, it might be a good idea to find the longest string length first.*

*The rest is very similar to the previous exercise.*

*The only difference is that now you have to determine whether to add a letter from a string, or a space.*

*Solution:*

```python
lengths = []
for string in strings:
    lengths.append(len(string))
length = max(lengths)

for i in range(length):
    line = ""
    for string in strings:
        if i >= len(string):
            line += " "
        else:
            line += string[i]
    print(line)
```

*user solves exercise, runs code, reaches Final Text*

#### Final Text

You have mastered nested lists and how to combine them with nested loops. Brilliant!

*user reaches next Page*

</details>

**Comment by alexmojaki** [comment]
Regarding the `strings[-1][-1]` exercise:
- I think the previous example input is fine as is
- I think they should have to find `strings[-2][-1]` or `strings[-1][-2]` so that they have to think about which one is which
- Maybe they should be required to do it in a single expression to make sure they learn the 'new' syntax?
- Should they be allowed to use `len` if they can't remember `[-1]`, i.e. `strings[len(strings) - 1][len(strings[len(strings) - 1]) - 1]`? Maybe if they use `len` (successfully or not) we should remind them the intended syntax exactly?

Regarding `__copyable__  # ??????`: keep the same matrix as before, then the loop is the only new thing being typed. In particular the `for row in matrix: for num in row` is an important new pattern worth typing. But I like that it's not square, so rather use that rectangular matrix in the first example.

Regarding representing people as lists: I still like mentioning that sublists can be different lengths, but this is a weird example. In fact in general I don't think we should be looking at lists that contain a mixture of types. Doing that is generally a bad idea and this encourages it. You can see how it immediately raises hairy questions like how to specify Charlie's hobby but not a pet. Plus it makes code unreadable. The correct way to handle data like this is a class or dictionary, or at least a short fixed length tuple.

> Write a program to print every string in a nested list strings that contains the given word.

Let's motivate this example. For example, previously I suggested that each list represents a book, and each string is a page.

In fact, let's use this example throughout. Instead of a matrix of numbers before, use a nested list of strings. From the very beginning make the sublists have unequal lengths. It's not a point that needs to be lingered on. Make them retrieve a letter with triple subscripting, and maybe use a triple nested loop to print all letters.

It's now plausible that they can use nested loops to see if a string contains a word, e.g.

```python
for sublist in strings:
    for string in sublist:
        for i in range(len(string) - len(word)):
            substring = ""
            for j in range(len(word)):
                substring += string[i + j]
            if substring == word:
                print(string)

```

I don't think students should attempt that, but if they forget about `in`, they might think they're supposed to before they check the hints. So maybe let's say outside the hints "Remember that there is a specific way to check if a string contains another string. If you can't remember how, Google it!"

> Next, print a boolean for each sublist in strings to indicate whether that sublist contains word

We should explain why `word in sublist` doesn't work.

Overall this is good! Only real problem was that mixed types stuff. With the suggested changes, I think we can jump to a PR now.

**Comment by spamegg1** [comment]
Should this issue be closed? @alexmojaki
