### ISSUE TITLE
Server error when module has no such attribute

### ISSUE THREAD

**Issue by matan-h** [alexmojaki/futurecoder#113]
Server error:
When I write file with for example:
```python
import os
print(os.not_found(""))
```
I should have received only  and AttributeError (module 'os' has no attribute 'not_found').
Instead I got a server error:
```
Method: run_code
Request data: {
    "code": "import os\nprint(os.not_found(\"\"))",
    "source": "editor",
    "page_index": 6,
    "step_index": 1
}

Traceback (most recent call last):
  File "/usr/src/app/backend/main/workers/worker.py", line 29, in execute
  File "my_program.py", line 2, in <module>
    print(os.not_found(""))
AttributeError: module 'os' has no attribute 'not_found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/backend/main/workers/worker.py", line 111, in worker_loop
  File "/usr/src/app/backend/main/workers/worker.py", line 128, in run_code
  File "/usr/src/app/backend/main/workers/worker.py", line 72, in runner
  File "/usr/src/app/backend/main/workers/worker.py", line 32, in execute
  File "/usr/src/app/backend/main/workers/tracebacks.py", line 111, in format_exception
TypeError: can only concatenate str (not "bool") to str
```
I tried to report this with "Report error" tab but after I submitted the error the site is only thinking and I don't know if you got the report.

I tried other AttributeErrors, like:
```python
import sys
sys.not_found
```
Same result. 
Even:

```python
raise AttributeError("module '' has no attribute ''")
```
gives the same error.

I checked line 111 in tracebacks.py and found:
```python
 friendly_generic(e) + "\n\n" + friendly_runtime_cause(e)
```
so that means that "friendly_runtime_cause(e)" is probably boolean because if "friendly_generic(e)" was boolean the traceback message would be  "unsupported operand type(s)".

**Comment by alexmojaki** [comment]
Hi! Thanks for this excellently written error report!

> I tried to report this with "Report error" tab but after I submitted the error the site is only thinking

I don't know what "the site is only thinking" means, but indeed even if it succeeded it's not obvious, hence #16

> and I don't know if you got the report.

It would have created an issue here, so no.

What is your interest in futurecoder? Would you like to contribute code?

It should be quite easy to do a basic 'fix' for this which catches all exceptions while generating a message from friendly-traceback since that really shouldn't cause a crash. friendly_generic and friendly_runtime_cause are supposed to already do that but clearly a bit more work is needed.

In terms of a proper fix, friendly-traceback:

- Is changing very quickly
- Hasn't been upgraded to the latest version on futurecoder for a while
- Has apparently undergone some changes that I suggested which are very relevant to this issue but I haven't had a look at yet (https://github.com/aroberge/friendly-traceback/issues/117)

So a proper fix would probably:

- Take some time
- Be very interesting work
- Noticeably improve futurecoder's tracebacks
- Require pretty much rewriting the current code

**Comment by alexmojaki** [comment]
I have fixed the issue that prevented creating an issue here when submitting feedback. Thanks for bringing that to my attention.
