### ISSUE TITLE
Learn Javascript 

### ISSUE THREAD

**Issue by FranciscoImanolSuarez** [alexmojaki/futurecoder#215]
Is it possible to adapt the code editor to learn Javascript?

**Comment by alexmojaki** [comment]
The code editor is just one part. There's a lot of things that would have to be reimplemented in JS. For some of the features that make futurecoder stand out, like the debuggers, I don't even know what's possible in JS. And since there are already many free online interactive JS learning resources, I don't see much that could be added to this space. So I don't plan on supporting JS (or other languages) for the foreseeable future.
