### ISSUE TITLE
Too many hints

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/futurecoder#219]
I got some interesting feedback from a user: https://www.reddit.com/r/learnprogramming/comments/qjs3wh/i_built_futurecoder_a_100_free_and_interactive/hjsq5lc/?context=6

The essential bit:

> I revealed a hint, tried fiddling with what I had keeping the hint in mind, revealed another hint, etc. As for unshuffling the scrambled solution, no. By the time I got to those bits I was so frustrated that I just clicked through.

> In that particular challenge there were way too many [hints]. I think if you condensed them into a central idea instead of piece by piece it would have been better.

My response:

> In general I tried to make hints as gradual as possible to avoid revealing more information than needed. I see now I was thinking too simplistically and too many hints can backfire.

> What do you think of an indicator like "Shown 5 of 20 hints" (there were actually 20 hints in that exercise) so that users know what to expect and don't spend too long thinking about each hint and getting frustrated?

Their response:

> If you don't want to condense some then yes, an indicator would absolutely help.

> I generally like the gradual reveal of the hints because it allows me to think about how to get the solution without getting the answer. Sometimes I'll use to make sure I'm on the right track, which I think is what backfired on me in that exercise.

I can see now that I may have gone overboard with hints in some places. Going through the exercises and trimming them would probably be good. In the meantime adding an indicator about the number of hints seems like a good step. @vokounigor what do you think of this? Want to add an indicator? Should be very simple.

**Comment by alexmojaki** [comment]
Indicator was added in #224. Keeping this open to consider reducing the number of hints in some exercises.

**Comment by colevandersWands** [comment]
Maybe part of the problem is having users with different levels of experience and intuition.  IMO it would be impossible to get the hints right for everyone in on try, so what if there were an option to choose your "level" next to the hints button?  

Picking "easy" would queue up all the hints and extra support, picking "hard" would queue up fewer hints with less support.  and a few levels in between.  This would mean writing more hints, but I'm assuming that after putting in the effort to simplify the hints you already have an idea what the levels could be.  

The unknown for me is how hard it would be to implement the feature and if it would be worth the effort.

**Comment by alexmojaki** [comment]
I expect 'advanced' users to not need hints at all. And when a user was struggling (like in the original feedback) it seems that more hints can make things *worse* as information is revealed too slowly.

I'm going to close this for now, I actually don't see myself taking further action on it unless it comes up again. I think the indicator should make a big difference and I think some users will still appreciate having many small hints.
