### ISSUE TITLE
Translations to other languages

### ISSUE THREAD

**Issue by martinvilu** [alexmojaki/futurecoder#223]
Hi, I saw the post on /r/learnprogramming, and I want to help with the translation.

The best-case scenario is that you can provide a PO file.

But I haven't seen i18n in the project yet and if localization isn't a priority right now I can wait for my time to shine, by translating what I can from the project dependencies. (I'm currently halfway translating friendly-traceback PO file)

**Comment by alexmojaki** [comment]
Amazing! I had already identified you on GitHub, noticed all the forks, and started to write https://github.com/friendly-traceback/friendly-traceback/discussions/75 when I got notified about this issue!

**Comment by alexmojaki** [comment]
@martinvilu @aroberge @JLuc here is the project: https://poeditor.com/join/project?hash=Nn5IIJ1JV1

For now it 'only' contains the main text of each page. That's the bulk of the words so that people can start translating if they want, but there are many more smaller strings still to come, as well as the actual code to use the translations.

The msgid is generated in a way that should be much more stable than just using the English text.

Each term also has a comment with a link to that page. Unfortunately the link doesn't behave quite the way I want it to - futurecoder overrides it with the last page you visited. When it does that, press the browser back button.

As you can see it's all markdown. The special strings `__copyable__`, `__program__`, and `__program_indented__` should be left as is.

For now, don't translate any terms that contain any Python code or output that needs translating. I'm still thinking about a system for substituting that code intelligently so that you would only need to translate each variable and string literal once. If it only contains something like `print('---')` that wouldn't be translated, or `__program__`, then it's fine to translate.

Thank you in advance to all willing translators!

**Comment by aroberge** [comment]
@alexmojaki Sorry not to have acted on this yet, but I just don't have the time to work on it "right now".  I have a talk to prepare for friendly/friendly-traceback and a few items I want to get sorted out before.  I will get to it eventually though: I see a reminder for it every time I log in to poeditor.com. 😄

**Comment by alexmojaki** [comment]
Absolutely no worries and no pressure, this is a very long term project and I appreciate you even considering it. Good luck with your talk! Maybe give a shout out to futurecoder :wink: A link to https://futurecoder.io/course/#ide could be a quick and easy way for people to try friendly-traceback for themselves, particularly the error explanations.

**Comment by aroberge** [comment]
I've mentioned FurtureCoder three times in the last year (Pycon US talk, Pycon Australia talk, and talk given during a monthly Python France meeting.)  Here's a link to one of them: https://www.youtube.com/watch?v=NrXmEwSD8Cs&list=PLs4CJRBY5F1LKN2ISCse415LW5FZEjDX2&index=26

**Comment by alexmojaki** [comment]
> For now, don't translate any terms that contain any Python code or output that needs translating. I'm still thinking about a system for substituting that code intelligently so that you would only need to translate each variable and string literal once.

This is done now. The main chunks of text, with msgids like `pages.*.steps.*.text`, now have most code blocks (not inline code) replaced by `__code{i}__` in the translations. Turning those back into code blocks and then translating them will happen inside futurecoder. You only need to translate each variable name and string literal, which have msgids like `code_bits.*`.

The `.text` terms have comments showing the contents of each `__code__` block, as well as links (sort of) to the terms of code bits used in those blocks. Similarly the code bits terms have comments linking to the text terms containing them and show the code blocks. Unfortunately it seems that these comments can't be updated on poeditor by subsequent uploads, so they may go out of date after a while.

Let me know if this system feels like it makes things difficult for you. Keep in mind that the code blocks get significantly longer towards the end, and what's there so far doesn't even cover all the code blocks that would need translating.

**Comment by alexmojaki** [comment]
See https://github.com/alexmojaki/futurecoder/wiki/How-to-write-translations-for-futurecoder

**Comment by alexmojaki** [comment]
There's obviously plenty of translation still to be done and always will be, but I don't think this issue needs to remain open.
