### ISSUE TITLE
Improve the lists chapter

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/futurecoder#34]
Towards the end of the chapter on lists, particularly on the page `FunctionsAndMethodsForLists`, the quality is not great. A lot of information is dumped on the user and it's not easy for them to process it. There's lots of reading and not much interactivity.

Here is what I'm trying to accomplish:

- Summarise the essential things you can do with lists, like len and append. This is to refresh their memory in the moment and also provide one easy place that they can come back to later if they need a reminder.
- Show that there are many other useful functions available for lists (and also strings). They *don't* actually need to memorise any of these - they just need to know that many useful functions exist, and have a vague sense of the kinds of things they do so that when they encounter a use case they have a chance of guessing that a function might exist and can be found with google.
- Show how to look things up, e.g. with google.

The reason there are no exercises and only a light encouragement to "Try them out in the shell" is because remembering the actual functions is not important. But the way the page is now is lots of dry, boring reading. That's bad.

I'm looking for opinions on how to deal with this. Should we:

- Add some steps where users are required to try out functions in the shell, or even complete exercises? This makes the section less boring. But it also puts more pressure on the user to learn information that is not essential at this stage. I've described my concerns about that [here](https://github.com/alexmojaki/futurecoder/issues/23#issuecomment-668052076). Maybe it's fine, and this is just the time to learn those things.
- Emphasise more and earlier that they don't need to memorise the functions so that they feel comfortable skimming through the list if it's boring.
- Do something completely different? I'm keen for ideas.

Then there's this section:

> Note that in most cases, methods which modify a list in place (`append`, `insert`, `remove`) merely return `None`, while the remaining functions/methods return a new useful value without changing the original argument. The only exception is the `pop` method.
> 
> Modifying a value directly is called *mutation* - types of values which can be mutated are *mutable*, while those that can't are *immutable*. Strings are immutable - they don't have any methods like `append` or even subscript assignment. You simply can't change a string - you can only create new strings and use those instead. That means that this is a useless statement on its own:
> 
>     word.upper()
> 
> The string referred to by `word` isn't modified, instead `word.upper()` returned a new string which was immediately discarded. If you want to change the value that `word` refers to, you have to assign a new value to the variable:
> 
>     word = word.upper()
> 
> Or you can use `word.upper()` immediately in a larger expression, e.g.
> 
>     if word.lower() == 'yes':

This is all very important information that is worth learning properly. Adding some interactive steps (e.g. showing that `word.upper()` on its own doesn't change `word`) would be great. I think the only reason I didn't was that I was tired and lazy. It should maybe be on its own page, the reason I hesitate is that I refer to method names like `pop` and it's useful to be able to scroll up and see the definitions of those methods. They can still use the Previous and Next buttons if the pages are separated though, and that might even be better.

The pages `EqualsVsIs` and `ModifyingWhileIterating` are also heavy reading and not great, but maybe less of a priority.

**Comment by spamegg1** [comment]
Here is a crude first attempt. This is going to take a lot of polishing.

## Improve the List chapter

### Functions and Methods for Lists and Strings

#### Step 1

Let's review how to work with lists. Suppose we have a list `nums = [7, 3, 2]`. You can use:

- **`len`**: Returns the number of elements. `len(nums)` is `3`.
- **`append`**: Add an element to the end of the list. `nums.append(4)` changes the list to `[7, 3, 2, 4]`.
- **`range`**: `range(n)` is an object similar to the list of numbers from 0 to `n - 1`. In particular, `range(len(nums))` is like `[0, 1, 2]`.
- **`subscripting`**: Get a value at an index. `nums[0]` is 7, `nums[1]` is 3, `nums[2]` is 2.
- **`+`**: Concatenates lists. `nums + [4, 5]` is `[7, 3, 2, 4, 5]`.

Let's use some this knowledge in an exercise. Write some code that prints out each index and its corresponding value in `nums`. For example if `nums = [7, 3, 2]`, your code should print out

```python
The value at index 0 is: 7
The value at index 1 is: 3
The value at index 2 is: 2    
```

*Hints*

*Use `len`, `range` and subscripting.

*Solution looks like:*

```python
nums = [7, 3, 2]
for i in range(len(nums)):
    print("The value at index", i, "is:", nums[i])
```

*user types and runs code, reaches next Step*

#### Step 2

Here are some new things. 

- **`subscript assignment`**: Set a value at an index. Type and run the following code: 

  ```python
  nums = [7, 3, 2]
  nums[0] = 1
  print(nums)
  ```

  *user types and runs code, reaches next Step*

#### Step 3

As you can see, subscript assignment `nums[0] = 1` changes the list to `[1, 3, 2]` by changing the entry at index `0` (which was `7`) to `1`.

- **`join`**: Add a list of strings with a separator in between. This is a method of strings (the separator) which takes a list of strings as an argument. Try the following in the shell:

  ```python
  '--'.join(['apples', 'oranges', 'bananas'])
  ```

  *user types command in shell, reaches next Step*

#### Step 4

You can also use an empty string if you don't want a separator. For example `''.join(['apples', 'oranges', 'bananas'])` returns `"applesorangesbananas"`.

Some more useful functions and methods:

- **`sum`**: Add a list of numbers. `sum(nums)` is 6 (remember we changed `nums` to `[1, 3, 2]`).

- **`in`**: A comparison operator that checks if a value is in a list. `2 in nums` is `True`, but `4 in nums` is `False`.

- **`index`**: Returns the first index of a value in a list. Try in the shell: 

  ```python
  [7, 8, 9, 8].index(8)
  ```

  *user types command in shell, reaches next Step*

#### Step 5

What happens if the value isn't in the list? Try the following:

```python
[7, 8, 9, 8].index(5)
```

*user types command in shell, reaches next Step*

#### Step 6

As you can see `index` raises an error if the value isn't there.

You may recognize some of these functions and methods from your exercises. I assure you that those exercises were not pointless, as you've now learned valuable fundamental skills. 

For example, you can use `in` to check if a list contains 5, but there's no similarly easy way to check for a number bigger than 5.

### Suggestion: a new page here? (will cause data migration)

#### (title could be: How to Find Information with Google and more)

#### Step 7

It's useful to know these functions, but it's not easy to learn them all, and there's many more. A more important skill is being able to look things up. For example, here are some typical ways you might Google the above functions if you forgot their names:

- ```python
  append
  ```

  - python add element to list
  - python add item at end of list

- ```python
  len
  ```

  - python size of list
  - python number of elements in list
  - python how many characters in string

- ```python
  join
  ```

  - python combine list of strings with separator
  - python add together list of strings with string in between

- ```python
  sum
  ```

  - python add list of numbers
  - python total of numbers

- ```python
  in
  ```

  - python check if list contains value
  - python test if list has element

- ```python
  index
  ```

  - python get position of element
  - python get index of value

Let's practice this skill now. Using Google, find a function/method that returns the value in a list which is bigger than any other value. For example, given the list `[21, 55, 4, 91, 62, 49]`, it will return `91`. You should write the answer in the shell as a single small expression. For example, if you were looking for the function `sum`, you could write `sum([21, 55, 4, 91, 62, 49])`. Don't solve this manually with a loop.

*Solution is:*

```python
max([21, 55, 4, 91, 62, 49])
```

*user types and runs code, reaches next Step*

#### Step 8

Good find! Let's do one more. Consider this program:

```python
nums = [1, 2, 3, 4, 5]
nums.append(9)
print(nums)
```

This changes `nums` so that it prints:

```python
[1, 2, 3, 4, 5, 9]
```

But suppose you don't want the 9 to be at the end, you want it to go between the second and third elements, so the output is:

```python
[1, 2, 9, 3, 4, 5]
```

Replace the middle line (i.e. the call to `append`) with the right function/method call to do that.

*Solution:*

```python
nums.insert(2, 9)
```

*user types and runs code, reaches next Step*

#### Step 8

Perfect!

It can also be useful to Google things like "python list tutorial", e.g. if:

- Googling a specific method has failed so you want to find it manually.
- You're still confused about lists after this course.
- It's been a while since you learned about lists and you need a reminder.
- You're struggling to solve a problem with lists and you need to go back to basics and strengthen your foundations.

There are also ways to find information without any googling. Try `dir([])` in the shell.

*user types command in shell, reaches next Step*

#### Step 9

`dir()` returns a list of the argument's attributes, which are mostly methods. Many will start with `__` which you can ignore for now - scroll to the end of the list and you'll see some familiar methods.

### Suggestion: a new page here? (will cause data migration)

### (title could be: More list and string methods and functions, understanding mutation)

#### Step 10

Here are a few more useful functions/methods. 

Suppose `nums = [28, 99, 10, 81, 59, 64]`.

- **`sorted`**: Takes an iterable and returns a list of the elements in order. `sorted(nums)` returns `[10, 28, 59, 64, 81, 99]`.
- **`pop`**: Removes and returns an element at a given index. `nums.pop(3)` removes `nums[3]` (`81`) from the list and returns it. Without an argument, i.e. just `nums.pop()`, it will remove and return the last element.
- **`remove`**: Removes the first occurrence of the given element. `nums.remove(10)` will leave `nums` as `[28, 99, 81, 59, 64]`. Raises an error if the value doesn't exist. Equivalent to `nums.pop(nums.index(10))`.
- **`count`**: Returns the number of times the argument appears in the list. `[1, 2, 3, 2, 7, 2, 5].count(2)` is 3.

Note that in most cases, methods which *modify a list in place* (`append`, `insert`, `remove`) merely return `None`, while the remaining functions/methods return a new useful value without changing the original argument. The only exception is the `pop` method.

Let's put some of this to use. Write code that prints the smallest and the largest numbers in a given list of integers, *but without using `max` or `min`!* For example, if `nums = [28, 99, 10, 81, 59, 64]` then your code should print:

```python
Smallest: 10
Largest: 99
```

*Hints:*

*Use `sorted` and `pop`.*

*Solution looks like:*

```python
nums = [28, 99, 10, 81, 59, 64]
print("Smallest:", sorted(nums).pop(0))
print("Largest:", sorted(nums).pop())
```

*user types and runs code, reaches next Step*

#### Step 11

Excellent work!

You've already seen that `len` and subscripting work with strings, a bit as if strings are lists of characters. Strings also support some of the new methods we've learned, not just for characters but for any substring. 

For example, try the following in the shell. What do you expect it to return?

```python
'the' in 'feed the dog and the cat'
```

*user runs command in the shell, reaches next Step*

#### Step 12

`in` works on strings like it does on lists! The command returned `True` because `the` occurs in `feed the dog and the cat` as a *substring*.

How about `count` and `index`? Type and run this code in the editor:

```python
string = 'feed the dog and the cat'
print(string.count('the'))
print(string.index('the'))
```

*user types and runs code, reaches next Step*

#### Step 13

Again these two methods also work on strings similar to how they work on lists. `index` returns the *beginning index* of the search word `'the'` in the longer string, which is `5`:

|  0   |  1   |  2   |  3   |  4   | **5** |  6   |  7   |  8   | ...  |
| :--: | :--: | :--: | :--: | :--: | :---: | :--: | :--: | :--: | :--: |
|  f   |  e   |  e   |  d   |      | **t** |  h   |  e   |      | ...  |

Modifying a value directly is called *mutation* - types of values which can be mutated are *mutable*, while those that can't are *immutable*. Lists are mutable. Strings are immutable - they don't have any methods like `append` or even subscript assignment. Try and see for yourself in the shell:

```python
'Python'.append('is cool!')
```

*user types command in shell, reaches next Step*

#### Step 14

You simply can't change a string - you can only create new strings and use those instead. That means that this is a useless statement on its own:

```python
word.lower()
```

The string referred to by `word` isn't modified, instead `word.lower()` returned a new string which was immediately discarded. If you want to change the value that `word` refers to, you have to assign a new value to the variable. Type and run in the editor:

```python
word = "Python rocks!"
new_word = word.upper()
print(word)
print(new_word)
```

*user types and runs code, reaches next Step*

#### Step 15

Observe that `word.lower()` does not change the original `word`, because strings are immutable!

You can also use `word.lower()` immediately in a larger expression, e.g.

```python
if word.lower() == 'yes':
```

**Comment by alexmojaki** [comment]
Thanks for taking a stab at this!

For step 1, I think let's leave that part as it is without the exercise. They've covered this material pretty thoroughly and I don't want to bore them with a trivial exercise. I just want to give a brief reminder and a page that they can come back to if they've forgotten the syntax.

For steps 2 to 6, I'm going to quote what I wrote at the beginning:

> Show that there are many other useful functions available for lists (and also strings). They don't actually need to memorise any of these - they just need to know that many useful functions exist, and have a vague sense of the kinds of things they do so that when they encounter a use case they have a chance of guessing that a function might exist and can be found with google.
Show how to look things up, e.g. with google.

> The reason there are no exercises and only a light encouragement to "Try them out in the shell" is because remembering the actual functions is not important. But the way the page is now is lots of dry, boring reading. That's bad.

> I'm looking for opinions on how to deal with this. Should we:

> - Add some steps where users are required to try out functions in the shell, or even complete exercises? This makes the section less boring. But it also puts more pressure on the user to learn information that is not essential at this stage. I've described my concerns about that here. Maybe it's fine, and this is just the time to learn those things.
> - ...(other possible approaches)

Now I can see that you think we should go for the first option. That's fine, and you may be right. But I'm really not sure either way, and I would like to hear your actual thoughts and reasoning. Why do you think this is the better option? Is there a particular reason you left some concepts like `in` without interaction?

Yes, we should probably insert a new page about Google, I was just too lazy.

Did you change anything on that page? I can't tell.

> Note that in most cases, methods which modify a list in place (append, insert, remove) merely return None, while the remaining functions/methods return a new useful value without changing the original argument. The only exception is the pop method.

> Modifying a value directly is called mutation - types of values which can be mutated are mutable, while those that can't are immutable. Lists are mutable. Strings are immutable - they don't have any methods like append or even subscript assignment. Try and see for yourself in the shell:

These paragraphs belong together. You inserted a bunch of stuff between them and now the second one starts abruptly and weirdly. Move the first one down to join the second.

I think your example program with `word = "Python rocks!"` is a great addition and clearly shows the concept. Just change the variable name to something other than `word` or make the string actually only contain one word.

**Comment by spamegg1** [comment]
Got it, regarding Step 1. Will remove the exercise.

For Steps 2 to 6 I wanted to go with the "Do something completely different" option but I could not come up with any clever ideas. I think the first option is fine, so I went with that.

I left some concepts without interaction because from what you wrote, I got the impression that not all of them needed to be covered explicitly. I'd be happy to add interactions to them if you want.

I don't think I changed anything in the Google section.

I moved that paragraph to come right after the list methods section (which cover `pop` etc.) because that seemed to make more sense (normally it comes after the string stuff). I'll move it back.

**Comment by alexmojaki** [comment]
I find the exercise with `pop` a bit weird. The main purpose of `pop` is to remove an element, I don't like encouraging using it as an easy way to get the last element.

**Comment by spamegg1** [comment]
OK, I'll come up with something else for `pop`.

**Comment by alexmojaki** [comment]
> For Steps 2 to 6 I wanted to go with the "Do something completely different" option but I could not come up with any clever ideas. I think the first option is fine, so I went with that.

> I left some concepts without interaction because from what you wrote, I got the impression that not all of them needed to be covered explicitly. I'd be happy to add interactions to them if you want.

I want to think about this carefully and have some good reasons behind our choices.

It sounds like you're trying to compromise between "use interactivity to keep things interesting" and "avoid interactivity to keep things moving quickly since this isn't essential to learn" by making *some* things interactive. Which seems like a good idea. Maybe we should just stop and think which functions are most useful and worth learning about interactively. For example I think `in` is very useful and is worth a step more than some others.

**Comment by alexmojaki** [comment]
I have an idea for something completely different. I'm not sure if it's a good idea, or how exactly it should be implemented, but it's a thought. We describe a bunch of mini-exercises in random order, show them the solutions to all of them (plus some wrong answers) and they have to match up the exercises with the correct answers. Something like this:

- Get the second smallest element of a list
- Get the last element of a list
- Modify a list to move the first element to the end (length stays the same)
- Make a new list that's the original list but also has the first element repeated at the end (length increases by 1)
- 1 + 2 + 3 + ... + (x - 1) + x
- Equivalent to `x.remove(1)` (except it evaluates to `1` instead of `None`)
- Equivalent to `1 in x`

```python
sorted(x)[1]
sorted(x)[2]

x[len(x)]
x[len(x) - 1]
x[len(x) + 1]

x.append(x.pop(0))
x.pop(x.append(0))

x + [x[0]]
x + x[0]
[x] + x[0]

sum(range(x))
sum(range(x)) + 1
sum(range(x + 1))

x.pop(x.index(1))
x.index(x.pop(1))

x.count(1) > 0
x.count(1) > 1
x.count(1) >= 0
```

**Comment by spamegg1** [comment]
> It sounds like you're trying to compromise between "use interactivity to keep things interesting" and "avoid interactivity to keep things moving quickly since this isn't essential to learn" by making some things interactive. Which seems like a good idea. 

Yep, that was the idea.

> Maybe we should just stop and think which functions are most useful and worth learning about interactively. For example I think in is very useful and is worth a step more than some others.

OK. I'll try to come up with an `in` exercise.

Your "completely different" idea sounds interesting. Will it be a Parsons style exercise?

In the meantime I came up with a different exercise for Step 10 (`pop` stuff):

<details>
    <summary>Click to expand</summary>
Let's put some of this to use. In some college courses, your grade is calculated by dropping your lowest score, then averaging the remaining scores. Write code that prints the grade of a student whose exam scores are given. Do this without using a for loop. For example, if `scores = [28, 99, 10, 81, 59, 64]` then your code should print `66.2` (here `10` is the lowest score, so it's dropped).

*Hints:*

*There are many ways to solve this.*

*One way is to use `min`, `sum` and `len`. Add up the scores, subtract the lowest, and divide by the number of remaining scores.*

*Pay attention to the number of scores! When you drop the lowest score, the number of scores goes down by 1.*

*Another way uses `sorted` and `pop` instead of `min`. Sort the scores, pop the lowest score, then sum and average like before.*

*You can also get rid of the lowest score by using `min` and `remove`.*

*Solution looks like:*

```python
scores = [28, 99, 10, 81, 59, 64]
grade = (sum(scores) - min(scores)) / (len(scores) - 1)
print(grade)
```

*Another solution:*

```python
scores = [28, 99, 10, 81, 59, 64]
scores.remove(min(scores))
grade = sum(scores) / len(scores)
print(grade)
```

*Yet another:*

```python
scores = [28, 99, 10, 81, 59, 64]
sorted_scores = sorted(scores)
sorted_scores.pop(0)
print(sum(sorted_scores) / len(sorted_scores))
```

*user types and runs code, reaches next Step*
</details>

**Comment by alexmojaki** [comment]
I think a way we could do my idea is something like this:

Time for something different. You're going to do some mini-exercises involving these functions. And we'll give you the answers! Here they are:

```python
sorted(x)[1]
sorted(x)[2]

x[len(x)]
x[len(x) - 1]
x[len(x) + 1]

x.append(x.pop(0))
x.pop(x.append(0))

x + [x[0]]
x + x[0]
[x] + x[0]

sum(range(x))
sum(range(x)) + 1
sum(range(x + 1))

x.pop(x.index(1))
x.index(x.pop(1))

x.count(1) > 0
x.count(1) > 1
x.count(1) >= 0
```

Well, the correct answers are in there, but there's also a lot of wrong answers. Find the correct answer for each exercise (just one line) and run it.

First exercise: enter an expression that's equivalent to `1 in x`.

-------

Great! Now write the expression that gives you the result of adding up all numbers from 1 to `x`, i.e. `1 + 2 + 3 + ... + (x - 1) + x`.

--------

etc.

--------

The hope is that these exercises would be easy, fun, and relaxing. So they learn something but they can get through it quickly and it's not too much pressure.

The disadvantage is that we would need to present all the functions in one go before the exercise to make it effective. That's a lot of information to dump on them at once. Maybe the exercise is interesting enough to compensate? Maybe I'm worrying too much and learning that these functions exist is already interesting?

If we go with this idea, `sum(x)/len(x)` could also be a good mini-exercise, maybe that's better than `sum(range(x+1))`.

Another possibility is to have an exercise to sort a list, and we immediately give them the solution as a Parsons problem. The correct solution is:

```python
lst = [1, 3, 2, 0, 9, 4]
sorted_list = []
for _ in range(len(lst)):
    value = min(lst)
    index = lst.index(value)
    lst.pop(index)
    sorted_list.append(value)
print(sorted_list)
```

The Parsons problem could also contain lots of incorrect lines (distractors) to make it more challenging.

I'm currently leaning towards the mini-exercises as our best option, but I'm not sure. What do you think?

**Comment by spamegg1** [comment]
I think mini-exercises is better. It's a very different way of thinking for the users. It requires some backwards thinking, seeing the solution first and working back to connect it to a solution. Also it trains them to read someone else's code with possible bugs in it.

I understand your worry; if there is information overload the tendency will be to blindly copy and run each line. We need to make sure the list is not too long. Maybe split them up into separate questions. Maybe encourage them to test out stuff in the shell first. Would it help to make this a multiple choice quiz (with radio buttons)?

**Comment by alexmojaki** [comment]
Ok here's a proposal outline:

1. Remove `.join` from the chapter. It's an outlier.
2. Do two sets of 4 mini-exercises. Each set introduces 4 new concepts (but not one per exercise).
3. Start the chapter with the same recap of 5 familiar concepts.
4. Emphasise difference between creating a new expression with + and modifying with append.
5. Introduce subscript assignment, index, pop, and remove.
6. First set of exercises:

```python
# Arrow comments indicate correct answers
# If you change anything about this list note it precisely and tell me
x[len(x)] = x[0]
x[len(x) - 1] = x[0]  # <--
x[len(x) + 1] = x[0]
x + x[0]
[x] + x[0]
x + [x[0]]  # <--
[x] + [x[0]]
x + x.pop(0)
[x] + x.pop(0)
x + [x.pop(0)]
[x] + [x.pop(0)]
x.pop(x.append(0))
x.append(x.pop(0))  # <--
x.append(x[0])
x.append(x.index(0))
x.index(x.append(0))
x.pop(x.index(0))  # <--
x.index(x.pop(0))

# [a, b, c] -> [b, c, a]
x.append(x.pop(0))

# [a, b, c] -> [a, b, a]
x[len(x) - 1] = x[0]
# After this exercise teach about x[-1], x[-2] etc.

# [a, b, c] -> [a, b, c, a]
x + [x[0]]

# Equivalent to x.remove(0)
x.pop(x.index(0))
```

7. Introduce count, `in`, sorted, sum
8. Next set of exercises:

```python

sum(len(x))
sum(range(x))
sum(range(len(x)))
sum(len(range(x)))
sum(range(x)) + 1
sum(range(x + 1))
sum(x) / len(x)
sum(x) / range(x)
sum(x) / range(len(x))
sum(x) / len(range(x))
sorted(x)[1]
sorted(x)[2]
sorted(x)[-1]
sorted(x)[-2]
x.count(1) >= 0
x.count(1) > 0
x.count(1) > 1


# equivalent to 1 in x
x.count(1) > 0

# average of x
sum(x) / len(x)

# total of 1 to x
sum(range(x + 1))

# second smallest value
sorted(x)[1]
    sorted
    subscript
```

9. Talk about similar string methods and mutation. Could probably still use some work but not too important.
10. Talk about google and stuff on next page. Remember to remove .join.

**Comment by spamegg1** [comment]
OK, will work these into the draft. It'll take some time.
Just to clarify, the user will see ALL of the choices BEFORE the first of the 4 exercises, right?

**Comment by alexmojaki** [comment]
Yes, they will see all of these:

```
x[len(x)] = x[0]
x[len(x) - 1] = x[0]  # <--
x[len(x) + 1] = x[0]
x + x[0]
[x] + x[0]
x + [x[0]]  # <--
[x] + [x[0]]
x + x.pop(0)
[x] + x.pop(0)
x + [x.pop(0)]
[x] + [x.pop(0)]
x.pop(x.append(0))
x.append(x.pop(0))  # <--
x.append(x[0])
x.append(x.index(0))
x.index(x.append(0))
x.pop(x.index(0))  # <--
x.index(x.pop(0))
```

**Comment by spamegg1** [comment]
Here is a second draft.
(Originally I wrote some hints but then removed them. These exercises are supposed to be short and relaxing, and they can see the solutions, hints are probably overkill.)

<details>
    <summary>Click to expand</summary>

## Improve the List chapter, Second Draft

### Page 1: Functions and Methods for Lists and Strings

#### Step 1

Let's review how to work with lists. Suppose we have a list `nums = [1, 2, 3]`. You can use:

- **`len`**: Returns the number of elements. `len(nums)` is `3`.
- **`append`**: Add an element to the end of the list. `nums.append(4)` changes the list to `[1, 2, 3, 4]`.
- **`range`**: `range(n)` is an object similar to the list of numbers from 0 to `n - 1`. In particular, `range(len(nums))` is like `[0, 1, 2]`.
- **`subscripting`**: Get a value at an index. `nums[0]` is 1, `nums[1]` is 2, `nums[2]` is 3.
- **`+`**: Concatenates lists. `nums + [4, 5]` is `[1, 2, 3, 4, 5]`.

Note that `nums.append(4)` modifies the existing list `nums`, while `nums + [4, 5]` does not. To preserve the value of `nums + [4, 5]` we must assign it to a *new variable*. Type and run the following code in the editor:

```python
nums = [1, 2, 3]
new_nums = nums + [4, 5]
print('new_nums:', new_nums)
print('nums after +:', nums)
nums.append(4)
print('nums after append:', nums)
```

*user types and runs code, reaches next Step*

#### Step 2

As you see, `+` does not modify `nums`, but `append` does. (`new_nums` is not affected by the change in `nums`.)

Here are some new things. Try them out in the shell. Assume `nums = [1, 2, 3]`.

- **`subscript assignment`**: Set a value at an index. `nums[0] = 9` changes the list to ``[9, 2, 3]``.
- **`index`**: Returns the first index of a value in a list. `[7, 8, 9, 8].index(8)` is `1`. Raises an error if the value isn't there.
- **`pop`**: Removes and returns an element at a given index. `nums.pop(1)` removes `nums[1]` (which is `2`) from the list and returns it. Without an argument, i.e. just `nums.pop()`, it will remove and return the last element.
- **`remove`**: Removes the first occurrence of the given element. `nums.remove(3)` will leave `nums` as `[1, 2]`. Raises an error if the value doesn't exist. Equivalent to `nums.pop(nums.index(3))`.

Now you will solve four exercises about the new functions and methods you learned. Below is a list of correct and incorrect solutions mixed together. Each exercise has a one line solution, which is one of the lines below. In each exercise you need to find the correct line that achieves the result described. In all exercises assume you are given a list `x`.

```python
x[len(x)] = x[0]
x[len(x) - 1] = x[0]
x[len(x) + 1] = x[0]
x + x[0]
[x] + x[0]
x + [x[0]]
[x] + [x[0]]
x + x.pop(0)
[x] + x.pop(0)
x + [x.pop(0)]
[x] + [x.pop(0)]
x.pop(x.append(0))
x.append(x.pop(0))
x.append(x[0])
x.append(x.index(0))
x.index(x.append(0))
x.pop(x.index(0))
x.index(x.pop(0))
```

1. Find the line of code that modifies `x` to move the first element to the end, keeping the length of `x` the same. For example, if `x = ['a', 'b', 'c']` then the code should modify it to `['b', 'c', 'a']`. 

   Type the correct line from the list above in the editor, and then run the code.

*Solution:*

```python
x.append(x.pop(0))
```

*user types and runs line, reaches next Step*

#### Step 3

Good job. Next exercise:

2. Find the line of code that modifies `x` to overwrite the last element with the first element, keeping the length of `x` the same. For example, if `x = ['a', 'b', 'c']` then the code should modify it to `['a', 'b', 'a']`.

   Type the correct line from the list above in the editor, and then run the code.

*Solution:*

```python
x[len(x) - 1] = x[0]
```

*user types and runs code, reaches next Step*

#### Step 4

Excellent! 

You might realize that accessing the last element via `x[len(x) - 1]` is a bit cumbersome. The same can be achieved by `x[-1]`. Similarly, the second to last element `x[len(x) - 2]` is equivalent to `x[-2]`, and so on. Python allows us to count the index backwards too, starting at the last element with `-1`:

|   index   | first elt. | second elt. | third elt. | ... | 2nd to last elt. | last elt. |
| :-------: | :--: | :--: | :--: | :--: | :--: | :---: |
| forwards  |  `0`  |  `1`  |  `2`  | ...  |  `len(x) - 2`   | `len(x) - 1` |
| backwards | `-len(x)` | `-len(x) + 1` | `-len(x) + 2` | ... |  `-2`  | `-1` |

Next exercise:

3. Find the line of code that creates a new list, which is the same as the original list `x` but also has the first element repeated at the end (length increases by 1). For example, if `x = ['a', 'b', 'c']` then the code should make a new list that is equal to `['a', 'b', 'c', 'a']`.

   Type the correct line from the list above in the editor, and then run the code.

*Solution:*

```python
x + [x[0]]
```

*user types and runs line, reaches next Step*

#### Step 5

Great work. Now the final exercise:

4. Find the line of code that is equivalent to: `x.remove(0)`.

*Solution:*

```python
x.pop(x.index(0))
```

*user types and runs line, reaches next Step*

#### Step 6 (final text)

Great job!

You may recognize some of these functions and methods from your exercises. I assure you that those exercises were not pointless, as you've now learned valuable fundamental skills. 

### Page 2: More list and string methods and functions, understanding mutation (data migration!)

#### Step 7

Here are a few more useful functions/methods. 

Suppose `nums = [28, 99, 10, 81, 59, 64]`.

- **`count`**: Returns the number of times the argument appears in the list. `[1, 2, 3, 2, 7, 2, 5].count(2)` is 3.
- **`in`**: A comparison operator that checks if a value is in a list. `2 in nums` is `True`, but `4 in nums` is `False`.
- **`sorted`**: Takes an iterable and returns a list of the elements in order. `sorted(nums)` returns `[10, 28, 59, 64, 81, 99]`.
- **`sum`**: Add a list of numbers. `sum([1, 2, 3])` is 6.

Now you will solve another set of four exercises about these new functions and methods, just like before. Again, correct and incorrect solutions are mixed together, and you must choose the correct line of code, type it and run it. 

```python
sum(len(x))
sum(range(x))
sum(range(len(x)))
sum(len(range(x)))
sum(range(x)) + 1
sum(range(x + 1))
sum(x) / len(x)
sum(x) / range(x)
sum(x) / range(len(x))
sum(x) / len(range(x))
sorted(x)[1]
sorted(x)[2]
sorted(x)[-1]
sorted(x)[-2]
x.count(1) >= 0
x.count(1) > 0
x.count(1) > 1
```

1. Assume you are given a list `x` of numbers. Find the line of code that is equivalent to: `1 in x`.

   Type and run the correct line of code from the list above.

*Solution:*

```python
x.count(1) > 0
```

*user types and runs line of code, reaches next Step*

#### Step 8

Excellent work! Next exercise:

2. Assume you are given a list `x` of numbers. Find the line of code that calculates the average of all the numbers in `x`.

   Type and run the correct line of code from the list above. 

*Solution:*

```python
sum(x) / len(x)
```

*user types and runs line of code, reaches next Step*

#### Step 9

Good job! In this next exercise, assume that `x` is a number:

3. Find the line of code that computes the sum `1 + 2 + 3 + ... + x`.

   Type and run the correct line of code from the list above.

*Solution:*

```python
sum(range(x + 1))
```

*user types and runs line of code, reaches next Step*

#### Step 10

Excellent. And the last one:

4. Assume `x` is a list of numbers. Find the line of code that returns the *second smallest value* in `x`.

*Solution:*

```python
sorted(x)[1]
```

*user types and runs line of code, reaches next Step*

#### Step 11

You've already seen that `len` and subscripting work with strings, a bit as if strings are lists of characters. Strings also support some of the new methods we've learned, not just for characters but for any substring. 

For example, try the following in the shell. What do you expect it to return?

```python
'the' in 'feed the dog and the cat'
```

*user runs command in the shell, reaches next Step*

#### Step 12

`in` works on strings like it does on lists! The command returned `True` because `the` occurs in `feed the dog and the cat` as a *substring*.

How about `count` and `index`? Type and run this code in the editor:

```python
string = 'feed the dog and the cat'
print(string.count('the'))
print(string.index('the'))
```

*user types and runs code, reaches next Step*

#### Step 13

Again these two methods also work on strings similar to how they work on lists. `index` returns the *beginning index* of the search word `'the'` in the longer string, which is `5`:

|  0   |  1   |  2   |  3   |  4   | **5** |  6   |  7   |  8   | ...  |
| :--: | :--: | :--: | :--: | :--: | :---: | :--: | :--: | :--: | :--: |
|  f   |  e   |  e   |  d   |      | **t** |  h   |  e   |      | ...  |

Note that in most cases, methods which *modify a list in place* (`append`, `insert`, `remove`) merely return `None`, while the remaining functions/methods return a new useful value without changing the original argument. The only exception is the `pop` method.

Modifying a value directly is called *mutation* - types of values which can be mutated are *mutable*, while those that can't are *immutable*. Lists are mutable. Strings are immutable - they don't have any methods like `append` or even subscript assignment. Try and see for yourself in the shell:

```python
'Python'.append(' is cool!')
```

*user types command in shell, reaches next Step*

#### Step 14

You simply can't change a string - you can only create new strings and use those instead. That means that this is a useless statement on its own:

```python
word.lower()
```

The string referred to by `word` isn't modified, instead `word.lower()` returned a new string which was immediately discarded. If you want to change the value that `word` refers to, you have to assign a new value to the variable. Type and run in the editor:

```python
sentence = "Python rocks!"
new_sentence = sentence.upper()
print(sentence)
print(new_sentence)
```

*user types and runs code, reaches next Step*

#### Step 15 (final text)

Observe that `sentence.upper()` does not change the original `sentence`, because strings are immutable!

You can also use `word.lower()` immediately in a larger expression, e.g.

```python
if word.lower() == 'yes':
```

### Page 3: How to Find Information with Google, and more

#### Steps 16-19 (I did not change anything here)

</details>

**Comment by alexmojaki** [comment]
I'd like to remove all mentions of print with multiple arguments from the text and teach f-strings instead, see #61. And in any case I'd like to only mention that after lists. For now just `print(new_nums)` etc, no labels.

Remove "Equivalent to nums.pop(nums.index(3))", they have to figure that out now.

I think we can't have something like " In all exercises assume you are given a list x." We need to make these actual ExerciseSteps, so the user needs to write a program like:

```python
x = [1, 2, 3]
x = x + [x[0]]
print(x)
```

We can easily enforce that the solution is exactly 3 statements.

I think all the list exercises should be on one page, and the string methods and mutability on another.

> You may recognize some of these functions and methods from your exercises. I assure you that those exercises were not pointless, as you've now learned valuable fundamental skills.

Put this after the second set of functions, and restore the other text that went with it.

Otherwise, I think this looks great! I think you can move to a PR. You'll probably find that tables don't work in markdown, just leave a placeholder there for now.

**Comment by spamegg1** [comment]
Excellent, will do.
