### ISSUE TITLE
Chapter about quotes and f-strings

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/futurecoder#61]
I'd like to add a chapter, tentatively called "A bit more about strings", after the chapter on lists and before nested loops, with two pages:

1. Double quotes. So far I've only used single quotes, leaving students probably wondering how to write an apostrophe inside a string. They will learn about escape sequences later. This page should mention that both single and double quotes are allowed and they do the same thing. `"abc" == 'abc'` (they should actually see this), they both get reduced to single quotes in the shell, and become the same thing when printed. Double quotes are useful when you want your string to contain single quotes and vice versa. All pages prior to this page should only use single quotes, which I think currently isn't the case.
2. f-strings. In the nested loops chapter I introduce `print` with multiple arguments which was a bad idea. Instead students should be shown the basics of f-strings and encouraged to use them instead of `+` in most situations. In particular they should be shown that adding a string and a number doesn't work but f-strings get around this. Then f-strings should be used in following pages where sensible, including modifying existing pages.

@BobAnkh you seemed interested in writing course content. This should be fairly simple, want to give it a go?

**Comment by BobAnkh** [comment]
Ok, I will try to do it in these days.

**Comment by alexmojaki** [comment]
Great, thanks! See https://github.com/alexmojaki/futurecoder/blob/master/how_to_contribute.md#how-to-implement-course-content-in-python for some guidance on how writing a chapter works.

**Comment by BobAnkh** [comment]
Ok, thank you for your guidance. I will see it.

**Comment by Kush1101** [comment]
@alexmojaki If the issue is open for contribution, I'd like to give it a try.

**Comment by BobAnkh** [comment]
@alexmojaki I'm so sorry that I'm busy this week. So if @Kush1101 want to do it, I think it is better to let him take this.

**Comment by alexmojaki** [comment]
Hi @Kush1101, nice to meet you! Thanks for being willing to contribute!

@BobAnkh don't feel bad, I am grateful that you want to help. This issue is not urgent.

Ideally I would like everyone to have something they can work on (when they have time) to maximise productivity. It would be a pity if @Kush1101 took this issue and then when @BobAnkh had time there was nothing for him to do.

Here are some other topics I'd like to cover soon:

- Nested lists, under the nested loops chapter
- `input()`
- Types (see the points in #23)

Are either of you interested in trying to write something about any of these topics? If not then that's fine too, it's just a suggestion. No one should say they will attempt something they don't want to do.

@Kush1101 if these don't appeal to you, then you can take this issue, just let me know.

**Comment by Kush1101** [comment]
I can take the `input()` chapter. It will be relatively short and easy. So it will allow me to familiarize myself with the whole project.

**Comment by Kush1101** [comment]
@alexmojaki any update?

**Comment by alexmojaki** [comment]
Sorry I thought you were just going to work on the `input()` chapter, were you waiting for a comment from me?

**Comment by Kush1101** [comment]
Yeah, I wasn't sure if I were to proceed or not. My bad 😅

**Comment by alexmojaki** [comment]
@BobAnkh @Kush1101 are you still planning on working on these? @spamegg1 wanna take over?

**Comment by BobAnkh** [comment]
Sorry for not having enough time to do this work in recent months. 😭 Let someone else who is available to take over this. @alexmojaki

**Comment by spamegg1** [comment]
Hmm OK I'll take over. I actually don't know f-strings myself. It'll be fun to learn

**Comment by alexmojaki** [comment]
Great! f-strings are very simple. We only want to teach the absolute basics, no formatting.

**Comment by spamegg1** [comment]
Since I don't know this topic fully, before I write the markdown draft, I made a rough outline of it showing the structure:
<details>
    <summary>Click to expand</summary>

## Chapter: More on strings, string formatting, printing

### Page 1: Single and Double (and Triple-Double???) Quotes in Strings

#### Step

Mention that we have been using single quotes for strings up until now. We can't use apostrophe in a string with single quotes. Introduce double strings.

#### Step

Show that there is no difference between single and double quoted strings. They both get reduced to single-quoted strings in the shell.

#### Step

Use apostrophe inside a double quoted string. Show that a double-quoted string with an apostrophe inside remains double-quoted in the shell.

#### Step ???

Triple-double quotes??? Show that they can be used to write long multi line text. They still get reduced to single quotes with a bunch of `\n`s in the shell, and to double quotes if it contains an apostrophe.

#### Step

One exercise.

#### Final Text

Rough guideline?: single quotes for short strings, double quotes for longer or with apostrophe, and triple-double only for special occasions.

### Page 2: Using f-strings

#### Step

Basics of f-strings. Define a few variables, and combine them in a single-quoted string. Print result.

#### Step

Also show it in the shell. Use `F` instead of `f` to show it's still valid (use double-quotes this time).

#### Step

Show using numbers (and maybe some other things? like `.lower()` etc.) inside f-strings. Mention how arithmetic expressions get calculated inside an f-string and then get converted to strings.

#### Step???

Show a multi line f-string? Too complicated???

#### Step???

Use a list and the `**` unpacking mechanism inside an f-string? Too complicated???

#### Step

One exercise.

#### Final Text

Encourage them to use it instead of `+`



## Then... fix the following chapters!!!

Separate PR for this???

</details>

**Comment by alexmojaki** [comment]
No triple quotes or newlines.

> single quotes for short strings, double quotes for longer

No, use whatever quotes you feel like, unless of course your string contains quote characters.

I didn't know F was possible. Don't show it.

> Use a list and the ** unpacking mechanism inside an f-string

I don't know what you're talking about.

> Encourage them to use it instead of +

In particular show that str + int doesn't work.

**Comment by spamegg1** [comment]
My bad, `**` only works with `.format()` and dictionaries:
```python
>>> person = {'name': 'Eric', 'age': 74}
>>> "Hello, {name}. You are {age}.".format(**person)
'Hello, Eric. You are 74.'
```

OK, it'll be a few days until the first draft. Stay tuned!

**Comment by spamegg1** [comment]
First crude draft:
<details>
    <summary>Click to expand</summary>

## Chapter: More on strings, quotes, introducing f-strings



### Page 1: Single and Double (and Triple-Double???) Quotes in Strings

#### Step

We have been defining strings using single quotes up until now, like:

```python
name = 'Alice'
```

What happens if we want to define a string that contains an apostrophe? Run this program:

```python
restaurant = 'Alice's Diner'
print(restaurant)
```

*user types and runs code, reaches next Step*

#### Step

So we can't use an apostrophe as we like in a string with single quotes. The apostrophe counts as a single quote and therefore acts as a *closing quote* of a string definition `'Alice'`. Then the remaining text `s Diner'` is invalid syntax and Python does not understand it.  

Thankfully Python allows us to define strings in another way, using double quotes `"` instead: 

```python
name = "Alice"
```

Go ahead and fix the `restaurant` string using double quotes, and rerun the program.

*user runs code in the editor, reaches next Step*

#### Step

You might wonder if there is a difference between strings defined using single quotes and using double quotes. `print` gets rid of the quotes, so compare them in the shell using `==`:

```python
'Alice' == "Alice"
```

*user runs line in the shell, reaches next Step*

#### Step

As you can see Python considers the same string defined by single or double quotes as the same. They would both print `Alice`. The quotes act as a sort of *container* for the string. The equality operator `==` compares the *contents* of the strings. 

Is there any visual difference? Evaluate the string `"Alice"` in the shell.

*user runs line in the shell, reaches next Step*

#### Step

So `"Alice"` evaluates to `'Alice'` in the shell. What about a string that contains an apostrophe? Evaluate `"Alice's Diner"` in the shell.

*user runs line in the shell, reaches next Step*

#### Step

This time `"Alice's Diner"` evaluated to itself in the shell, because in this case the double quotes could not be replaced by single quotes. (Of course `print` would still drop the *defining* double quotes.)

For this exercise, write a program that defines a string named `principle`, which contains the following text from the Zen of Python:

```
Special cases aren't special enough to break the rules.
```

and then prints it.

*Hints:*

*How should you define the string?*

*With single quotes, or with double quotes?*

*Solution:*

```python
principle = "Special cases aren't special enough to break the rules."
print(principle)
```

*user types and runs code in the editor, reaches next Step*

#### Step

Now write a program that defines a string named `quote` which contains the following quote:

```python
"Talk is cheap. Show me the code." - Linus Torvalds
```

and then prints it exactly (including the double quotes!)

*Hints:*

*Think simple! How would you normally do this?*

*If a string contains a single quote, we must use double quotes to define it.*

*What if the string contains double quotes?*

*Solution:*

```python
quote = '"Talk is cheap. Show me the code." - Linus Torvalds'
print(quote)
```

*user types and runs code in the editor, reaches Final Text*

#### Final Text

From now on you can use either single or double quotes to define your strings, however you like it. If your string contains `'` then use `"` to define it; and vice versa.

### Page 2: Introducing f-strings

#### Step

So far we have been combining strings by concatenating them using `+`, like `'Hello' + ' ' + 'World'`. However this gets a bit cumbersome. Python has a better way to do this using a syntax called *f-strings*. Run the following program:

```python
friend = "Bob"
language = 'Python'
print(f'You have a friend named {friend} and your favorite programming language is {language}.')
```

*user types and runs code in the editor, reaches next Step*

#### Step

The syntax of an f-string starts with `f` followed by a string. The string can contain names of variables inside curly brackets `{}`. When printed, they will be replaced with the values of those variables! The variables can be strings, or even numbers as you can see.

In addition to variables, an f-string can also contain Python expressions to be evaluated inside curly brackets. We can evaluate an f-string in the shell like any other expression. Run this line in the shell:

```python
f"2 to the power 6 equals {2*2*2*2*2*2}."
```

*user runs line in the shell, reaches next Step*

#### Step

As you can see we can define an f-string using double quotes too, like we can a normal string. Moreover numbers that are calculated inside an f-string are then converted to strings.

One advantage of f-strings is combining different types (like numbers and strings) to build new strings which we can't do with concatenation using `+`. For example, try this program:

```python
name = "Alice"
age = 20
print("Hello " + name + ". You are " + age + " years old.")
```

#### Step

This fails because we cannot use `+` between a string `". You are "` and the number `age`. As an exercise, fix the last line using an f-string.

*Hints:*

*Solution:*

```python
name = "Alice"
age = 20
print(f'Hello {name}. You are {age} years old.')
```



*user types and runs code in the editor, reaches Final Text*

#### Final Text

Excellent!

From now on, you are encouraged to use f-strings instead of `+` to build up your strings where possible.

</details>

**Comment by alexmojaki** [comment]
I think leave out the steps 'Evaluate the string "Alice" in the shell.' and 'Evaluate "Alice's Diner" in the shell.'. Maybe just briefly hint at the difference so they can try it out themselves it they want, but if they're not experts at what the shell displays it's fine. The page is already quite long and detailed for a very small topic. Knowing how to print the strings they want is the important part.

Why do you want users to define a variable with a specific name like `principle`? Why not just make them print the string?

The strings that they need to print should be copyable to prevent typos.

We need a better example than adding three literals together like `'Hello' + ' ' + 'World'`.

`f"2 to the power 6 equals {2*2*2*2*2*2}."` is not pleasant to type in exactly. It's also especially mathematical.

Side note, I've just realised some of the new steps in the lists chapter like `sorted([28, 99, 10, 81, 59, 64])` are not fun to type in either. We should fix that.

I think it would be better if the chapter started with this one:

```python
__copyable__
name = "Alice"
age = 20
print("Hello " + name + ". You are " + age + " years old.")
```

That makes it clear from the beginning why they should be interested in this, beyond just a prettier syntax. Then show them the fixed version.

Then demonstrate a better example of expressions inside f-strings. Here's one idea:

```python
x = 1
y = 2
f"{x} + {y} = {x + y}"
```

However this is basically identical to the times table exercise later on, not sure if that's a good or bad thing.

Maybe a way to make an exercise more interesting would be if they had to fix an especially broken program, e.g.

```python
people = ["Alice", "Bob", "Charlie"]
print('There are' + people.length() + 'people waiting, the first one's name is' + people.1)
```

Now they need to use f-strings, correct quotes, and the correct list concepts.

**Comment by spamegg1** [comment]
Second draft:
<details>
    <summary>Click to expand</summary>

## Chapter: More on strings, quotes, introducing f-strings

### Page 1: Single and Double Quotes in Strings

#### Step

We have been defining strings using single quotes up until now, like:

```python
name = 'Alice'
```

What happens if we want to define a string that contains an apostrophe? Run this program:

```python
restaurant = 'Alice's Diner'
print('We are going to ' + restaurant + ' for lunch.')
```

*user types and runs code, reaches next Step*

#### Step

So we can't use an apostrophe as we like in a string with single quotes. The apostrophe counts as a single quote and therefore acts as a *closing quote* of a string definition `'Alice'`. Then the remaining text `s Diner'` is invalid syntax and Python does not understand it.  

Thankfully Python allows us to define strings in another way, using double quotes `"` instead: 

```python
name = "Alice"
```

Go ahead and fix the `restaurant` string using double quotes, and rerun the program.

*user runs code in the editor, reaches next Step*

#### Step

You might wonder if there is a difference between strings defined using single quotes and using double quotes. `print` gets rid of the quotes, so compare them in the shell using `==`:

```python
'Alice' == "Alice"
```

*user runs line in the shell, reaches next Step*

#### Step

As you can see Python considers the same string defined by single or double quotes as the same. They would both print `Alice` (the shell will display `"Alice"` as `'Alice'` though). The quotes act as a sort of *container* for the string. The equality operator `==` compares the *contents* of the strings. 

For this exercise, write a program that prints the following text from the Zen of Python:

```
(copyable)
Special cases aren't special enough to break the rules.
```

*Hints:*

*How should you define the string?*

*With single quotes, or with double quotes?*

*Solution:*

```python
print("Special cases aren't special enough to break the rules.")
```

*user types and runs code in the editor, reaches next Step*

#### Step

Now write a program that prints the following quote exactly (including the double quotes):

```
(copyable)
"Talk is cheap. Show me the code." - Linus Torvalds
```

*Hints:*

*Think simple! How would you normally do this?*

*If a string contains a single quote, we must use double quotes to define it.*

*What if the string contains double quotes?*

*Solution:*

```python
print('"Talk is cheap. Show me the code." - Linus Torvalds')
```

*user types and runs code in the editor, reaches Final Text*

#### Final Text

From now on you can use either single or double quotes to define your strings, however you like it. If your string contains `'` then use `"` to define it; and vice versa.

### Page 2: Introducing f-strings

#### Step

So far we have been combining strings by concatenating them using `+`, like: 

```python
name = "Alice"
friend = 'Bob'
meal = "lunch"
print(name + " went to " + meal + " with " + friend + '.')
```

However this gets a bit cumbersome and it does not let us easily combine strings and numbers. Run the following program:

```python
__copyable__
name = "Alice"
age = 20
print("Hello " + name + ". You are " + age + " years old.")
```

*user types and runs code in the editor, reaches next Step*

#### Step

This fails because we cannot use `+` between the string `". You are "` and the number `age`. 

Thankfully Python allows us to overcome this with *f-strings*. The syntax of an f-string starts with `f` followed by a string: 

```python
name = "Alice"
print(f'Hello {name}!')
```

The string can contain names of variables inside curly brackets `{}`. When printed, they will be replaced with the values of those variables. The variables can be strings, or even numbers!

As an exercise, fix the last line of the previous program in the editor by using an f-string.

*Hints:*

*Solution:*

```python
name = "Alice"
age = 20
print(f'Hello {name}. You are {age} years old.')
```

#### Step

In addition to variables, an f-string can also contain Python expressions to be evaluated inside curly brackets. We can evaluate an f-string in the shell like any other expression. Run this line in the shell:

```python
f"{2 * 3 + 4}"
```

*user runs line in the shell, reaches next Step*

#### Step

As you can see we can define an f-string using double quotes too, like we can a normal string. Moreover numbers that are calculated inside an f-string are then converted to strings.

Here is a broken program:

```python
people = ["Alice", "Bob", "Charlie"]
print('There are' + people.length() + 'people waiting, the first one's name is' + people.1 + '.')
```

Fix this by using an f-string and correcting the wrong syntax. Your solution should work for any list of strings named `people`. It should print the correct number of people in the list, and the name of the first person in the list. It should also have proper spacing between words. For example, in the above case it should print:

```
There are 3 people waiting, the first one's name is Alice.
```

*Hints:*

*There are three problems with the expression inside `print`.*

*There is a problem with the syntax that finds the number of people.*

*Then one of the strings has a problem with the quotes.*

*Also there is a problem with the syntax that finds the first person's name.*

*Did you forget to properly use curly brackets in your f-string?*

*Solution:*

```python
people = ["Alice", "Bob", "Charlie"]
print(f"There are {len(people)} people waiting, the first one's name is {people[0]}")
```

*user types and runs code in the editor, reaches Final Text*

#### Final Text

Excellent!

From now on, you are encouraged to use f-strings instead of `+` to build up your strings where possible.

</details>

**Comment by alexmojaki** [comment]
:+1: time for a PR!

**Comment by spamegg1** [comment]
Coming right up!
What should I do about the page numbering? Should I make it `c07_quotes_fstrings.py` and renumber the rest?

**Comment by alexmojaki** [comment]
`c07_a_bit_more_about_strings.py`?

**Comment by spamegg1** [comment]
OK, and I'll renumber the rest.

**Comment by spamegg1** [comment]
How to use `__copyable__` with plain text that doesn't follow Python syntax?
```
    __copyable__
    Special cases aren't special enough to break the rules.
```
gives
```
File "/usr/src/app/backend/main/utils/__init__.py", line 168, in run
    node.set("class", node.get("class") + " copyable")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by spamegg1** [comment]
Adding f-strings to Chapters 8, 9, 10, some TODOs, and a few other things:
<details>
    <summary>Click to expand </summary>

# Replacing `print` with multiple arguments with `f-strings`

## Chapter 8

### Page: Introducing Nested Loops

#### Steps 1, 2, 3 combined into one:

You've seen that the indented body of an `if` or a loop can contain any kind of statement, including more `if` statements and loops. In particular a loop can contain another loop. Here's an example:

```python
for letter in "ABC":
    print(letter)
    for number in range(4):
        print(f'{letter}, {number}')
    print('---')
```

Make sure you fully grasp what's going on. `print(letter)` and `print('---')` each run 3 times, because their indentation puts them in the *outer loop*. `print(f'{letter}, {number}')` is called 3 × 4 = 12 times, because it's in the *inner loop* `for number in range(4):` which has 4 iterations but is itself in the outer loop so it runs 3 times.

*Predicted output:*

- ```
  A 0
  A 1
  A 2
  A 3
  ---
  B 0
  B 1
  B 2
  B 3
  ---
  C 0
  C 1
  C 2
  C 3
  ---
  ```

- ```
  A
  A 0
  A 1
  A 2
  A 3
  ---
  B
  B 0
  B 1
  B 2
  B 3
  ---
  C
  C 0
  C 1
  C 2
  C 3
  ---
  ```

- ```
  A
  A 1
  A 2
  A 3
  A 4
  ---
  B
  B 1
  B 2
  B 3
  B 4
  ---
  C
  C 1
  C 2
  C 3
  C 4
  ---
  ```

- ```
  A
  B
  C
  ---
  A 0
  B 0
  C 0
  ---
  A 1
  B 1
  C 1
  ---
  A 2
  B 2
  C 2
  ---
  A 3
  B 3
  C 3 
  ```

- `Error`

#### Step 4: multiplication table exercise

*Solution changes to:*

```python
for num1 in range(1, 13):
    for num2 in range(1, 13):
        print(f'{num1} x {num2} = {num1 * num2}')
    print('----------')
```

*One hint changes from:*

```python
Use `print()` with several arguments separated by commas to print several things on one line.
```

*to:*

```python
Use an f-string with several variables.
```

*Put an f-string into `solution` method too, because they might reveal it.*

*What about `program` in the message step? Put f-strings there too? I guess it doesn't matter.*

*TODO message: catch left += 1 in inner loop instead of the outer loop*

*(I'm still learning the `check` method, any suggestions appreciated)*

```python
class adding_one_in_wrong_loop(MessageStep):
	"""
You added 1 to your outer loop variable at the wrong place!
Where should you do that instead to fix it?
	"""

    def program(self):
        for left in range(12):
	        for right in range(12):
                left += 1
                right += 1
                print(f'{left} x {right} = {left * right}')
        	print('----------')

    def check(self):
        # really heavy-handed solution, must be a better way
        result = ''
        for left in range(12):
        	for right in range(12):
                left += 1
                right += 1
                result += f"{left} x {right} = {left * right}"
                result += '\n'
        	result += '----------\n'
        return self.result == result
```

#### Step 5: player vs. player exercise

*Solution changes to:*

```python
players = ["Alice", "Bob", "Charlie"]
for player1 in players:
    for player2 in players:
        if player1 != player2:
            print(f'{player1} vs {player2}')
```

*Add one more test case to the exercise step?*

#### Step 6: password cracking exercise

*Solution changes to:*

```python
letters = 'ABCD'
for c1 in letters:
    for c2 in letters:
        for c3 in letters:
            for c4 in letters:
                print(f'{c1}{c2}{c3}{c4}')
```

*TODO message: catch spaces between letters in output, e.g. print(c1, c2, c3, c4)*

*Should we still do this TODO even after switching to f-strings?*

#### Step 7: upside down triangle exercise

No changes here.

#### Step 8: bonus challenge

*Solution changes to:*

```python
players = ['Charlie', 'Alice', 'Dylan', 'Bob']
for i in range(len(players)):
    for j in range(len(players)):
        if i < j:
            print(f'{players[i]} vs {players[j]}')
```

No other changes in this Chapter.

## Chapter 9

### Page: Defining Functions

#### Step 1: define greet

*Program changes to:*

```python
def greet(name):
    print(f"Hello {name}!")

greet("Alice")
greet("Bob")
```

This doesn't have `print` with multiple arguments, but is it still better off with an f-string?

#### Steps 2, 3, 4:

Similar changes as above. Good or bad?

#### Steps 5, 6, 7:

No changes here.

### Page: Testing Functions

#### Step 4: surround exercise

This doesn't use `print`. Should it still be changed to:

```python
def surround(string, sides):
    return f'{sides}{string}{sides}'
```

I'm guessing not.

#### Step 5: alert exercise

This has a message step specifically forbidding f-strings, so not touching this.

*TODO message: catch return inside loop*

```python
class catch_return_inside_loop(MessageStep):
    """
You placed your `return` statement in the wrong place!
Pay attention to your indentations.
            """

    def solution(self):
        def surround(string, sides):
            return sides + string + sides

        def alert(string: str, level: int):
            string = surround(string, ' ')
            for _ in range(level):
                string = surround(string, '!')
                return string

        return alert

    def check(self):  # is this right?
        for node in ast.walk(self.tree):
            if isinstance(node, ast.For):
                for inner in ast.walk(node):
                    if isinstance(inner, ast.Return):
                        return True
        return False

```

## Chapter 10

### Page: Introducing Or

#### Last Step: `is_valid_percentage` exercise

Should we disallow `not` too? I was able to pass with:

```python
return not (x < 0 or x > 100)
```

This uses `or` as intended but uses `not` which is not covered yet.

No other changes!

</details>

**Comment by alexmojaki** [comment]
Thank you, this looks great! Excited for the PR. Some small comments:

range(1, 13) hasn't been covered.

Your method for adding_one_in_wrong_loop works fine, but rather make it an ExerciseStep as well as a MessageStep and put the full output in `tests`.

> Should we still do this TODO even after switching to f-strings?

No, that can be removed.

Use `+` instead of f-strings for `print(f'{c1}{c2}{c3}{c4}')` and `return f'{sides}{string}{sides}'`. In these cases f-strings aren't obviously better. f-strings are not good for the current method of revealing the solution, they get treated as one big token. In the other exercises f-strings are good.

Your implementation of `catch_return_inside_loop.check` is fine. Just add more explanation to the message.

> This uses or as intended but uses not which is not covered yet.

If they do that, good for them!

**Comment by spamegg1** [comment]
Awesome, making the PR soon.

**Comment by alexmojaki** [comment]
This was done in #98
